### ISSUE TITLE
Menambahkan Deskripsi Repositori dan Menambahkan Gaya

### ISSUE THREAD

**Issue by jefrydco** [roqib12/vuejs-fundamental#1]
Hi Mas Roqib, terima kasih telah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Roqib.

Namun saya mempunyai 2 saran untuk kode yg Mas kirim

1. Menambahkan Deskripsi Repositori
Agar repositori kita memiliki deskripsi, Mas bisa menambahkan berkas bernama `readme.md` di dalam direktori proyeknya Mas. Contohnya seperti ini Mas, https://github.com/jefrydco/jefrydco/blob/master/README.md

Hasilnya nanti akan seperti berikut:

![jefrydco](https://user-images.githubusercontent.com/20434351/89712748-0c804280-d9bd-11ea-8623-505f3e98fa15.png)

Pada berkas tersebut Mas juga dapat menuliskan deskripsi seputar aplikasi pada repo ini dan bagaimana cara menjalankannya. Mas dapat menggunakan penulisan [berformat markdown](https://guides.github.com/features/mastering-markdown/) atau HTML.

2. Menambahkan Gaya
Saya menyarankan Mas untuk menambahkan gaya, Mas dapat menggunakan kerangka kerja CSS Bootstrap, atau Tailwind atau kerangka kerja CSS yg lain. Atau Mas juga dapat menambahkan gaya tanpa menggunakan kerangka kerja CSS apapun.

Semangat Mas! 😄

**Comment by roqib12** [comment]
Terima Kasih Mas Masukkan dan Sarannya,
Insya Allah dikemudian hari nanti akan dipercantik
tampilannya karena sekarang masih dalam proses belajar juga

Pada tanggal Rab, 12 Agu 2020 pukul 18.42 Jefry Dewangga <
notifications@github.com> menulis:

**Comment by jefrydco** [comment]
Terima kasih kembali Mas, saya akan membiarkan isu ini terbuka ya nanti kalau Mas sudah ada waktu dan berkenan untuk memperbaiki, Mas bisa menutup isu ini. Semangat selalu Mas! 😄
